name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: pytest tests/

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t my-python-app:latest .

      # Step 6: Push Docker image to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push my-python-app:latest
